### ISSUE TITLE
Feature 2 - To-do Task Creation and Maintenance

### ISSUE THREAD

**Issue by yyutiw** [CSC207-2022F-UofT/course-project-32-things-to-do#1]
A task creation, deletion, and editing system.

- [x] Create code skeletons for all entities 
- [x] Implement main functionality of feature 
- [x] Complete UI portion and feature complete for first submission 
- [x] Fix bugs and work on feedback 
- [ ] Implement builder design pattern
