### ISSUE TITLE
Feature 6 - Grades Calculations and Progress Tracker

### ISSUE THREAD

**Issue by TiareMar** [CSC207-2022F-UofT/course-project-32-things-to-do#5]
Calculation of current grade, required average and progress bar for each course

Planned Timeline:
- [ ] Implement persistent data saving of grades (Nov 7)
- [ ] Grade calculations implemented (Nov 10)
- [ ] UI user input and display (Nov 14) 
- [ ] Bug Fixes and feedback improvement (Nov 21)
